openapi: 3.0.2
info:
  title: Example Mobile Products API
  description: |
    # Product concept
    This is a sample dummy data on Mobiles hosted on the `dummyjson.com` server.

  version: "1.0"

servers:
  - url: https://dummyjson.com/
    description: https
  - url: http://dummyjson.com/
    description: http
tags:
  - name: Mobiles
    description: details about the mobile phones.
paths:
  /products:
    get:
      tags:
        - Mobiles
      summary: Get the list of *all* mobile phones.
      operationId: GetMobiles
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                      example: 1
                    title:
                      type: string
                      example: iPhone 9
                    description:
                      type: string
                      example: An apple mobile which is nothing like apple
                    price:
                      type: integer
                      format: integer
                      example: 549
                    discountPercentage:
                      type: integer
                      format: int64
                      example: 12.96
                    rating:
                      type: integer
                      format: int64
                      example: 4.69
                    stock:
                      type: integer
                      format: int64
                      example: 94
                    brand:
                      type: string
                      example: Apple
                    category:
                      type: string
                      example: smartphones
                    thumbnail:
                      type: string
                      example: https://cdn.dummyjson.com/product-images/1/thumbnail.jpg
                    images:
                      type: string
                      example:
                        [
                          https://cdn.dummyjson.com/product-images/1/1.jpg,
                          https://cdn.dummyjson.com/product-images/1/2.jpg,
                          https://cdn.dummyjson.com/product-images/1/3.jpg,
                          https://cdn.dummyjson.com/product-images/1/4.jpg,
                          https://cdn.dummyjson.com/product-images/1/thumbnail.jpg,
                        ]
